from django.core.management.base import BaseCommand
from corruption_cases.models import Country

class Command(BaseCommand):
    help = 'Create initial countries data for the world map'

    def handle(self, *args, **options):
        self.stdout.write('Creating countries data...')
        
        # Complete list of world countries with ISO 3166-1 alpha-3 codes
        countries = [
            # Europe (50 countries)
            {'name': 'España', 'code': 'ESP'},
            {'name': 'Francia', 'code': 'FRA'},
            {'name': 'Alemania', 'code': 'DEU'},
            {'name': 'Italia', 'code': 'ITA'},
            {'name': 'Reino Unido', 'code': 'GBR'},
            {'name': 'Portugal', 'code': 'PRT'},
            {'name': 'Países Bajos', 'code': 'NLD'},
            {'name': 'Bélgica', 'code': 'BEL'},
            {'name': 'Suiza', 'code': 'CHE'},
            {'name': 'Austria', 'code': 'AUT'},
            {'name': 'Grecia', 'code': 'GRC'},
            {'name': 'Polonia', 'code': 'POL'},
            {'name': 'Suecia', 'code': 'SWE'},
            {'name': 'Noruega', 'code': 'NOR'},
            {'name': 'Dinamarca', 'code': 'DNK'},
            {'name': 'Finlandia', 'code': 'FIN'},
            {'name': 'Irlanda', 'code': 'IRL'},
            {'name': 'República Checa', 'code': 'CZE'},
            {'name': 'Rumanía', 'code': 'ROU'},
            {'name': 'Ucrania', 'code': 'UKR'},
            {'name': 'Rusia', 'code': 'RUS'},
            {'name': 'Hungría', 'code': 'HUN'},
            {'name': 'Bulgaria', 'code': 'BGR'},
            {'name': 'Croacia', 'code': 'HRV'},
            {'name': 'Serbia', 'code': 'SRB'},
            {'name': 'Eslovaquia', 'code': 'SVK'},
            {'name': 'Eslovenia', 'code': 'SVN'},
            {'name': 'Lituania', 'code': 'LTU'},
            {'name': 'Letonia', 'code': 'LVA'},
            {'name': 'Estonia', 'code': 'EST'},
            {'name': 'Luxemburgo', 'code': 'LUX'},
            {'name': 'Malta', 'code': 'MLT'},
            {'name': 'Chipre', 'code': 'CYP'},
            {'name': 'Islandia', 'code': 'ISL'},
            {'name': 'Albania', 'code': 'ALB'},
            {'name': 'Macedonia del Norte', 'code': 'MKD'},
            {'name': 'Montenegro', 'code': 'MNE'},
            {'name': 'Bosnia y Herzegovina', 'code': 'BIH'},
            {'name': 'Moldavia', 'code': 'MDA'},
            {'name': 'Bielorrusia', 'code': 'BLR'},
            {'name': 'Andorra', 'code': 'AND'},
            {'name': 'Liechtenstein', 'code': 'LIE'},
            {'name': 'Mónaco', 'code': 'MCO'},
            {'name': 'San Marino', 'code': 'SMR'},
            {'name': 'Vaticano', 'code': 'VAT'},
            {'name': 'Kosovo', 'code': 'XKX'},
            
            # Americas (35 countries)
            {'name': 'Estados Unidos', 'code': 'USA'},
            {'name': 'Canadá', 'code': 'CAN'},
            {'name': 'México', 'code': 'MEX'},
            {'name': 'Brasil', 'code': 'BRA'},
            {'name': 'Argentina', 'code': 'ARG'},
            {'name': 'Chile', 'code': 'CHL'},
            {'name': 'Colombia', 'code': 'COL'},
            {'name': 'Perú', 'code': 'PER'},
            {'name': 'Venezuela', 'code': 'VEN'},
            {'name': 'Ecuador', 'code': 'ECU'},
            {'name': 'Bolivia', 'code': 'BOL'},
            {'name': 'Paraguay', 'code': 'PRY'},
            {'name': 'Uruguay', 'code': 'URY'},
            {'name': 'Cuba', 'code': 'CUB'},
            {'name': 'República Dominicana', 'code': 'DOM'},
            {'name': 'Puerto Rico', 'code': 'PRI'},
            {'name': 'Costa Rica', 'code': 'CRI'},
            {'name': 'Panamá', 'code': 'PAN'},
            {'name': 'Guatemala', 'code': 'GTM'},
            {'name': 'Honduras', 'code': 'HND'},
            {'name': 'Nicaragua', 'code': 'NIC'},
            {'name': 'El Salvador', 'code': 'SLV'},
            {'name': 'Haití', 'code': 'HTI'},
            {'name': 'Jamaica', 'code': 'JAM'},
            {'name': 'Trinidad y Tobago', 'code': 'TTO'},
            {'name': 'Barbados', 'code': 'BRB'},
            {'name': 'Belice', 'code': 'BLZ'},
            {'name': 'Guyana', 'code': 'GUY'},
            {'name': 'Surinam', 'code': 'SUR'},
            {'name': 'Antigua y Barbuda', 'code': 'ATG'},
            {'name': 'Bahamas', 'code': 'BHS'},
            {'name': 'Dominica', 'code': 'DMA'},
            {'name': 'Granada', 'code': 'GRD'},
            {'name': 'San Vicente y las Granadinas', 'code': 'VCT'},
            {'name': 'Santa Lucía', 'code': 'LCA'},
            
            # Asia (48 countries)
            {'name': 'China', 'code': 'CHN'},
            {'name': 'Japón', 'code': 'JPN'},
            {'name': 'India', 'code': 'IND'},
            {'name': 'Corea del Sur', 'code': 'KOR'},
            {'name': 'Corea del Norte', 'code': 'PRK'},
            {'name': 'Indonesia', 'code': 'IDN'},
            {'name': 'Tailandia', 'code': 'THA'},
            {'name': 'Filipinas', 'code': 'PHL'},
            {'name': 'Vietnam', 'code': 'VNM'},
            {'name': 'Turquía', 'code': 'TUR'},
            {'name': 'Israel', 'code': 'ISR'},
            {'name': 'Palestina', 'code': 'PSE'},
            {'name': 'Arabia Saudí', 'code': 'SAU'},
            {'name': 'Irán', 'code': 'IRN'},
            {'name': 'Irak', 'code': 'IRQ'},
            {'name': 'Afganistán', 'code': 'AFG'},
            {'name': 'Pakistán', 'code': 'PAK'},
            {'name': 'Bangladesh', 'code': 'BGD'},
            {'name': 'Sri Lanka', 'code': 'LKA'},
            {'name': 'Nepal', 'code': 'NPL'},
            {'name': 'Bután', 'code': 'BTN'},
            {'name': 'Maldivas', 'code': 'MDV'},
            {'name': 'Myanmar', 'code': 'MMR'},
            {'name': 'Laos', 'code': 'LAO'},
            {'name': 'Camboya', 'code': 'KHM'},
            {'name': 'Malasia', 'code': 'MYS'},
            {'name': 'Singapur', 'code': 'SGP'},
            {'name': 'Brunéi', 'code': 'BRN'},
            {'name': 'Mongolia', 'code': 'MNG'},
            {'name': 'Kazajistán', 'code': 'KAZ'},
            {'name': 'Kirguistán', 'code': 'KGZ'},
            {'name': 'Tayikistán', 'code': 'TJK'},
            {'name': 'Turkmenistán', 'code': 'TKM'},
            {'name': 'Uzbekistán', 'code': 'UZB'},
            {'name': 'Azerbaiyán', 'code': 'AZE'},
            {'name': 'Georgia', 'code': 'GEO'},
            {'name': 'Armenia', 'code': 'ARM'},
            {'name': 'Líbano', 'code': 'LBN'},
            {'name': 'Siria', 'code': 'SYR'},
            {'name': 'Jordania', 'code': 'JOR'},
            {'name': 'Emiratos Árabes Unidos', 'code': 'ARE'},
            {'name': 'Kuwait', 'code': 'KWT'},
            {'name': 'Baréin', 'code': 'BHR'},
            {'name': 'Qatar', 'code': 'QAT'},
            {'name': 'Omán', 'code': 'OMN'},
            {'name': 'Yemen', 'code': 'YEM'},
            
            # Africa (54 countries)
            {'name': 'Egipto', 'code': 'EGY'},
            {'name': 'Libia', 'code': 'LBY'},
            {'name': 'Túnez', 'code': 'TUN'},
            {'name': 'Argelia', 'code': 'DZA'},
            {'name': 'Marruecos', 'code': 'MAR'},
            {'name': 'Sudán', 'code': 'SDN'},
            {'name': 'Sudán del Sur', 'code': 'SSD'},
            {'name': 'Etiopía', 'code': 'ETH'},
            {'name': 'Eritrea', 'code': 'ERI'},
            {'name': 'Somalia', 'code': 'SOM'},
            {'name': 'Yibuti', 'code': 'DJI'},
            {'name': 'Kenia', 'code': 'KEN'},
            {'name': 'Uganda', 'code': 'UGA'},
            {'name': 'Tanzania', 'code': 'TZA'},
            {'name': 'Ruanda', 'code': 'RWA'},
            {'name': 'Burundi', 'code': 'BDI'},
            {'name': 'República Democrática del Congo', 'code': 'COD'},
            {'name': 'República del Congo', 'code': 'COG'},
            {'name': 'República Centroafricana', 'code': 'CAF'},
            {'name': 'Camerún', 'code': 'CMR'},
            {'name': 'Chad', 'code': 'TCD'},
            {'name': 'Níger', 'code': 'NER'},
            {'name': 'Nigeria', 'code': 'NGA'},
            {'name': 'Benín', 'code': 'BEN'},
            {'name': 'Togo', 'code': 'TGO'},
            {'name': 'Ghana', 'code': 'GHA'},
            {'name': 'Burkina Faso', 'code': 'BFA'},
            {'name': 'Malí', 'code': 'MLI'},
            {'name': 'Senegal', 'code': 'SEN'},
            {'name': 'Mauritania', 'code': 'MRT'},
            {'name': 'Guinea', 'code': 'GIN'},
            {'name': 'Guinea-Bisáu', 'code': 'GNB'},
            {'name': 'Sierra Leona', 'code': 'SLE'},
            {'name': 'Liberia', 'code': 'LBR'},
            {'name': 'Costa de Marfil', 'code': 'CIV'},
            {'name': 'Gambia', 'code': 'GMB'},
            {'name': 'Cabo Verde', 'code': 'CPV'},
            {'name': 'Guinea Ecuatorial', 'code': 'GNQ'},
            {'name': 'Santo Tomé y Príncipe', 'code': 'STP'},
            {'name': 'Gabón', 'code': 'GAB'},
            {'name': 'Sao Tomé y Príncipe', 'code': 'STP'},
            {'name': 'Angola', 'code': 'AGO'},
            {'name': 'Zambia', 'code': 'ZMB'},
            {'name': 'Zimbabue', 'code': 'ZWE'},
            {'name': 'Botsuana', 'code': 'BWA'},
            {'name': 'Namibia', 'code': 'NAM'},
            {'name': 'Sudáfrica', 'code': 'ZAF'},
            {'name': 'Lesoto', 'code': 'LSO'},
            {'name': 'Suazilandia', 'code': 'SWZ'},
            {'name': 'Malaui', 'code': 'MWI'},
            {'name': 'Mozambique', 'code': 'MOZ'},
            {'name': 'Madagascar', 'code': 'MDG'},
            {'name': 'Mauricio', 'code': 'MUS'},
            {'name': 'Seychelles', 'code': 'SYC'},
            {'name': 'Comoras', 'code': 'COM'},
            
            # Oceania (14 countries)
            {'name': 'Australia', 'code': 'AUS'},
            {'name': 'Nueva Zelanda', 'code': 'NZL'},
            {'name': 'Papúa Nueva Guinea', 'code': 'PNG'},
            {'name': 'Fiyi', 'code': 'FJI'},
            {'name': 'Islas Salomón', 'code': 'SLB'},
            {'name': 'Vanuatu', 'code': 'VUT'},
            {'name': 'Samoa', 'code': 'WSM'},
            {'name': 'Tonga', 'code': 'TON'},
            {'name': 'Kiribati', 'code': 'KIR'},
            {'name': 'Tuvalu', 'code': 'TUV'},
            {'name': 'Nauru', 'code': 'NRU'},
            {'name': 'Palau', 'code': 'PLW'},
            {'name': 'Marshall', 'code': 'MHL'},
            {'name': 'Micronesia', 'code': 'FSM'},
        ]

        created_count = 0
        for country_data in countries:
            country, created = Country.objects.get_or_create(
                code=country_data['code'],
                defaults={'name': country_data['name']}
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created country: {country.name} ({country.code})'))
            else:
                self.stdout.write(f'Country already exists: {country.name} ({country.code})')

        self.stdout.write(self.style.SUCCESS(f'Successfully created {created_count} new countries.'))