# Generated by Django 4.2.7 on 2025-07-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corruptioncase',
            options={'ordering': ['-amount', '-date', '-created_at']},
        ),
    ]
