# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0002_alter_corruptioncase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='author_name',
            field=models.CharField(blank=True, help_text='Nombre del autor del artículo', max_length=200),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='is_annual_amount',
            field=models.BooleanField(default=False, help_text='¿Es esta cantidad un gasto anual?'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='publication_type',
            field=models.CharField(choices=[('article', 'Artículo'), ('case', 'Caso'), ('opinion', 'Artículo de Opinión'), ('report', 'Informe'), ('investigation', 'Investigación'), ('news', 'Noticia'), ('video', 'Vídeo'), ('other', 'Otro')], default='article', help_text='Tipo de publicación', max_length=50),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de comienzo del gasto (para calcular años de duración)', null=True),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='video_url',
            field=models.URLField(blank=True, help_text="URL del video (solo para publicaciones tipo 'video')", null=True),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(help_text='Maximum file size: 10MB', upload_to='cases/detail/'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in euros', max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 10MB', null=True, upload_to='cases/'),
        ),
    ]
