# Generated by Django 4.2.7 on 2025-09-27 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0004_add_missing_fields_and_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Imagen de publicación', 'verbose_name_plural': 'Imágenes de publicación'},
        ),
        migrations.AlterModelOptions(
            name='corruptioncase',
            options={'ordering': ['-amount', '-date', '-created_at'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='video_url',
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL externa para redirigir (para videos, artículos, noticias, etc.)', null=True, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_images', to='corruption_cases.corruptioncase', verbose_name='Publicación'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(help_text='Tamaño máximo: 10MB', upload_to='cases/detail/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Importe en euros', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='author_name',
            field=models.CharField(blank=True, help_text='Nombre del autor del artículo', max_length=200, verbose_name='Nombre del autor'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='corruption_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.corruptiontype', verbose_name='Tipo de corrupción'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='full_description',
            field=models.TextField(verbose_name='Descripción completa'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='is_annual_amount',
            field=models.BooleanField(default=False, help_text='¿Es esta cantidad un gasto anual?', verbose_name='Es importe anual'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Es destacado'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Tamaño máximo: 10MB', null=True, upload_to='cases/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='political_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.politicalparty', verbose_name='Partido político'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='publication_type',
            field=models.CharField(choices=[('article', 'Artículo'), ('case', 'Caso'), ('opinion', 'Artículo de Opinión'), ('report', 'Informe'), ('investigation', 'Investigación'), ('news', 'Noticia'), ('video', 'Vídeo'), ('other', 'Otro')], default='article', help_text='Tipo de publicación', max_length=50, verbose_name='Tipo de publicación'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='sources',
            field=models.TextField(help_text='Enlaces a fuentes, separados por líneas nuevas', verbose_name='Fuentes'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de comienzo del gasto (para calcular años de duración)', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='tags',
            field=models.ManyToManyField(blank=True, to='corruption_cases.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
