# Generated by Django 4.2.7 on 2025-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0004_add_missing_fields_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL externa para redirigir (para artículos, noticias, etc.)', null=True),
        ),
    ]
