# Generated by Django 4.2.7 on 2025-09-27 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0005_add_external_url_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Tamaño máximo: 10MB', upload_to='cases/detail/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Imagen de publicación',
                'verbose_name_plural': 'Imágenes de publicación',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='corruptioncase',
            options={'ordering': ['-importe', '-fecha', '-fecha_creacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='corruption_type',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='is_annual_amount',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='political_party',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='corruptioncase',
            name='video_url',
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='descripcion_completa',
            field=models.TextField(default='Sin descripción completa', verbose_name='Descripción completa'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='descripcion_corta',
            field=models.TextField(default='Sin descripción', max_length=500, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='Es destacado'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='es_importe_anual',
            field=models.BooleanField(default=False, help_text='¿Es esta cantidad un gasto anual?', verbose_name='Es importe anual'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='corruption_cases.tag', verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='fecha',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de comienzo del gasto (para calcular años de duración)', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='fuentes',
            field=models.TextField(default='Sin fuentes', help_text='Enlaces a fuentes, separados por líneas nuevas', verbose_name='Fuentes'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Tamaño máximo: 10MB', null=True, upload_to='cases/', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importe en euros', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='nombre_autor',
            field=models.CharField(blank=True, help_text='Nombre del autor del artículo', max_length=200, verbose_name='Nombre del autor'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='partido_politico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.politicalparty', verbose_name='Partido político'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='tipo_corrupcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.corruptiontype', verbose_name='Tipo de corrupción'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='tipo_publicacion',
            field=models.CharField(choices=[('article', 'Artículo'), ('case', 'Caso'), ('opinion', 'Artículo de Opinión'), ('report', 'Informe'), ('investigation', 'Investigación'), ('news', 'Noticia'), ('video', 'Vídeo'), ('other', 'Otro')], default='article', help_text='Tipo de publicación', max_length=50, verbose_name='Tipo de publicación'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='url_externa',
            field=models.URLField(blank=True, help_text='URL externa para redirigir (para videos, artículos, noticias, etc.)', null=True, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='CaseImage',
        ),
        migrations.AddField(
            model_name='imagenpublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='corruption_cases.corruptioncase', verbose_name='Publicación'),
        ),
    ]
