# Generated by Django 4.2.7 on 2025-10-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0005_alter_caseimage_options_alter_corruptioncase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del país')),
                ('code', models.CharField(help_text='Código ISO 3166-1 alpha-3', max_length=3, unique=True, verbose_name='Código ISO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País al que se destina el dinero público', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corruption_cases.country', verbose_name='País destino'),
        ),
    ]
