# Generated by Django 4.2.7 on 2025-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0007_make_amount_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de publicación del contenido', null=True, verbose_name='Fecha de publicación'),
        ),
    ]
