# Generated by Django 4.2.7 on 2025-11-10 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption_cases', '0008_add_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2018',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2018', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2018'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2019',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2019', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2019'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2020',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2020', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2020'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2021',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2021', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2021'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2022', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2022'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2023',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2023', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2023'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2024',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2024', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2024'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='amount_2025',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe específico para el año 2025', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe 2025'),
        ),
    ]
